# docker-compose.yml

version: '3.8'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    networks:
      - elastic

  auth:
    build:
      context: .
      dockerfile: ./apps/authorization/Dockerfile
    command: npm run docker:auth
    env_file:
      - ./apps/authorization/.envDocker
    depends_on:
      - postgres-auth
      - rabbitmq
    networks:
      - elastic
      - auth

  meetup:
    build:
      context: .
      dockerfile: ./apps/meetup/Dockerfile
    command: npm run docker:meetup
    env_file:
      - ./apps/meetup/.envDocker
    depends_on:
      - postgres-meetup
      - rabbitmq
      - elasticsearch
    networks:
      - elastic
      - meetup

  gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    command: npm run start:dev api-gateway
    env_file:
      - ./apps/api-gateway/.envDocker
    depends_on:
      - meetup
      - auth
      - rabbitmq
    ports:
      - 3000:3000
    networks:
      - elastic

  postgres-auth:
    image: postgis/postgis:13-3.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=957483
      - POSTGRES_DB=auth_microservice_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - auth:/var/lib/postgresql/data
    networks:
      - auth

  postgres-meetup:
    image: postgis/postgis:13-3.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=957483
      - POSTGRES_DB=meetup_microservice_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - meetup:/var/lib/postgresql/data
    networks:
      - meetup

  elasticsearch:
    image: elasticsearch:8.10.2
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'rxI2de2zHgnmKYkfToDh'
    networks:
      - elastic
    mem_limit: 1g
    cpus: '1'

  kibana:
    image: kibana:8.10.2
    environment:
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN="AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuMTpUUU9xaFl5c1JmZXBzVGJtMWhFZnl3"
    ports:
      - 5601:5601
    networks:
      - elastic
    mem_limit: 1g
    cpus: '1'

volumes:
  auth:
  meetup:


networks:
  auth:
  meetup:
  elastic:
