export const AUTH_MICROSERVICE = {
  RMQ_URL: process.env.RMQ_URL_AUTH_MICROSERVICE || 'amqp://localhost:5672',
  RMQ_QUEUE: process.env.RMQ_QUEUE_AUTH_MICROSERVICE || 'auth_microservice_queue',
};

export const AUTH_METADATA = {
  MP_REGISTRATION: 'REGISTRATION',
  MP_LOGIN: 'LOGIN',
  MP_VALIDATE_USER: 'VALIDATE_USER',

  MP_GET_ALL_USERS: 'GET_ALL_USERS',
  MP_GET_USER_BY_ID: 'GET_USER_BY_ID',
  EP_DELETE_USER_BY_ID: 'DELETE_USER_BY_ID',
};

export const ROLES_NAME = {
  USER: 'USER',
  ADMIN: 'ADMIN',
};
