export const AUTH_MICROSERVICE = {
  RMQ_URL: process.env.RMQ_URL_MEETUP_MICROSERVICE || 'amqp://localhost:5672',
  RMQ_QUEUE: process.env.RMQ_QUEUE_MEETUP_MICROSERVICE || 'auth_microservice_queue',
  RMQ_CLIENT_NAME: process.env.RMQ_CLIENT_NAME_MEETUP_MICROSERVICE || 'GATEWAY_MEETUP_SERVICE',
};

export const METADATA = {
  MP_REGISTRATION: 'REGISTRATION',
  MP_LOGIN: 'LOGIN',
  MP_VALIDATE_USER: 'VALIDATE_USER',
};
