export const METADATA = {
  MP_REGISTRATION: 'REGISTRATION',
  MP_LOCAL_LOGIN: 'LOCAL_LOGIN',
  MP_LOGOUT: 'LOGOUT',
  MP_REFRESH: 'REFRESH',
  MP_VALIDATE_USER: 'VALIDATE_USER',
  MP_YANDEX_LOGIN: 'YANDEX_LOGIN',

  MP_GET_ALL_USERS: 'GET_ALL_USERS',
  MP_GET_USER_BY_ID: 'GET_USER_BY_ID',
  MP_DELETE_USER_BY_ID: 'DELETE_USER_BY_ID',
  MP_UPLOAD_AVATAR: 'UPLOAD_AVATAR',
  MP_DOWNLOAD_AVATAR: 'DOWNLOAD_AVATAR',
  MP_REMOVE_AVATAR: 'REMOVE_AVATAR',

  MP_GET_ALL_MEETUPS: 'GET_ALL_MEETUPS',
  MP_GET_MEETUP_BY_ID: 'GET_MEETUP_BY_ID',
  MP_CREATE_MEETUP: 'CREATE_MEETUP',
  MP_UPDATE_MEETUP_BY_ID: 'UPDATE_MEETUP_BY_ID',
  MP_DELETE_MEETUP_BY_ID: 'DELETE_MEETUP_BY_ID',

  MP_GET_ALL_TAGS: 'GET_ALL_TAGS',
  MP_GET_TAG_BY_ID: 'GET_TAG_BY_ID',
  MP_CREATE_TAG: 'CREATE_TAG',
  MP_UPDATE_TAG_BY_ID: 'UPDATE_TAG_BY_ID',
  MP_DELETE_TAG_BY_ID: 'DELETE_TAG_BY_ID',

  MP_JOIN_TO_MEETUP: 'JOIN_TO_MEETUP',
  MP_LEAVE_FROM_MEETUP: 'LEAVE_FROM_MEETUP',
};
