export const METADATA = {
  MP_REGISTRATION: 'REGISTRATION',
  MP_LOGIN: 'LOGIN',
  MP_LOGOUT: 'LOGOUT',
  MP_REFRESH: 'REFRESH',
  MP_VALIDATE_USER: 'VALIDATE_USER',

  MP_GET_ALL_USERS: 'GET_ALL_USERS',
  MP_GET_USER_BY_ID: 'GET_USER_BY_ID',
  EP_DELETE_USER_BY_ID: 'DELETE_USER_BY_ID',

  MP_GET_ALL_MEETUPS: 'GET_ALL_MEETUPS',
  MP_GET_MEETUP_BY_ID: 'GET_MEETUP_BY_ID',
  MP_CREATE_MEETUP: 'CREATE_MEETUP',
  MP_UPDATE_MEETUP_BY_ID: 'UPDATE_MEETUP_BY_ID',
  EP_DELETE_MEETUP_BY_ID: 'DELETE_MEETUP_BY_ID',

  MP_GET_ALL_TAGS: 'GET_ALL_TAGS',
  MP_GET_TAG_BY_ID: 'GET_TAG_BY_ID',
  MP_CREATE_TAG: 'CREATE_TAG',
  MP_UPDATE_TAG_BY_ID: 'UPDATE_TAG_BY_ID',
  EP_DELETE_TAG_BY_ID: 'DELETE_TAG_BY_ID',

  MP_JOIN_TO_MEETUP: 'JOIN_TO_MEETUP',
  MP_LEAVE_FROM_MEETUP: 'LEAVE_FROM_MEETUP',
};
