export const APPLICATION = {
  PORT: process.env.PORT,
};

export const AUTH_MICROSERVICE = {
  RMQ_URL: process.env.RMQ_URL_MEETUP_MICROSERVICE,
  RMQ_QUEUE: process.env.RMQ_QUEUE_MEETUP_MICROSERVICE,
  RMQ_CLIENT_NAME: 'GATEWAY_AUTH_SERVICE',
};

export const MEETUP_MICROSERVICE = {
  RMQ_URL: process.env.RMQ_URL_MEETUP_MICROSERVICE,
  RMQ_QUEUE: process.env.RMQ_QUEUE_MEETUP_MICROSERVICE,
  RMQ_CLIENT_NAME: 'GATEWAY_MEETUP_SERVICE',
};

export const JWT = {
  ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  ACCESS_DURATION: process.env.JWT_ACCESS_DURATION,
  REFRESH_DURATION: process.env.JWT_REFRESH_DURATION,
};
