export const AUTH_MICROSERVICE = {
  RMQ_URL: process.env.RMQ_URL_AUTH_MICROSERVICE,
  RMQ_QUEUE: process.env.RMQ_QUEUE_AUTH_MICROSERVICE,
};

export const JWT = {
  ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  ACCESS_DURATION: process.env.JWT_ACCESS_DURATION,
  REFRESH_DURATION: process.env.JWT_REFRESH_DURATION,
};
